LeftAndMain:
  extra_requirements_css:
    - flat-cms/css/style.css
  extensions:
    - FlatCMSLeftAndMainExtension

SiteConfig:
  extensions:
    - FlatCMSSiteConfigExtension

CMSPagesController:
  awesome_icon: sitemap

AssetAdmin:
  awesome_icon: picture-o

ReportAdmin:
  awesome_icon: bar-chart

SecurityAdmin:
  awesome_icon: user

CMSSettingsController:
  awesome_icon: cog
