LeftAndMain:
  extra_requirements_css:
    - flat-cms/styles/css/style.css
  extensions:
    - FlatCMSLeftAndMainExtension

SiteConfig:
  extensions:
    - FlatCMSSiteConfigExtension

CMSPagesController:
  icon: sitemap

AssetAdmin:
  icon: picture-o

ReportAdmin:
  icon: bar-chart

SecurityAdmin:
  icon: users

CMSSettingsController:
  icon: cogs
